from django.urls import path
from .views import (
    login, me, grades, subjects, diary_entries, attendance, schedule,
    announcements, teacher_class_students, teacher_attendance, teacher_marks,
    teacher_add_grade, teacher_edit_grade, teacher_delete_grade,
    teacher_add_homework, teacher_delete_homework, teacher_homework_completions,
    behavioral_entries, teacher_add_behavioral, teacher_delete_behavioral,
    teacher_class_stats, teacher_student_comments, teacher_reports,
    admin_classes, admin_class_detail,
    admin_subjects, admin_subject_detail,
    admin_users, admin_user_detail,
    admin_teacher_assignments, admin_teacher_assignment_delete,
    admin_student_subjects, admin_student_subject_delete,
    admin_schedule, admin_schedule_detail,
    admin_csv_import,
    admin_impersonate,
    admin_stats,
    admin_events, admin_event_detail,
    admin_holidays, admin_holiday_detail,
    public_events,
    teacher_study_hall, teacher_study_hall_students, teacher_study_hall_attendance,
)

urlpatterns = [
    path("login/", login),
    path("me/", me),
    path("grades/", grades),
    path("subjects/", subjects),
    path("diary/", diary_entries),
    path("attendance/", attendance),
    path("schedule/", schedule),
    path("announcements/", announcements),
    path("behavioral/", behavioral_entries),
    path("teacher/class-students/", teacher_class_students),
    path("teacher/attendance/", teacher_attendance),
    path("teacher/marks/", teacher_marks),
    path("teacher/grades/add/", teacher_add_grade),
    path("teacher/grades/edit/", teacher_edit_grade),
    path("teacher/grades/delete/", teacher_delete_grade),
    path("teacher/homework/add/", teacher_add_homework),
    path("teacher/homework/delete/", teacher_delete_homework),
    path("teacher/homework/completions/", teacher_homework_completions),
    path("teacher/behavioral/add/", teacher_add_behavioral),
    path("teacher/behavioral/delete/", teacher_delete_behavioral),
    path("teacher/class-stats/", teacher_class_stats),
    path("teacher/student-comments/", teacher_student_comments),
    path("teacher/reports/", teacher_reports),
    # Admin
    path("admin/classes/", admin_classes),
    path("admin/classes/detail/", admin_class_detail),
    path("admin/subjects/", admin_subjects),
    path("admin/subjects/detail/", admin_subject_detail),
    path("admin/users/", admin_users),
    path("admin/users/detail/", admin_user_detail),
    path("admin/teacher-assignments/", admin_teacher_assignments),
    path("admin/teacher-assignments/delete/", admin_teacher_assignment_delete),
    path("admin/student-subjects/", admin_student_subjects),
    path("admin/student-subjects/delete/", admin_student_subject_delete),
    path("admin/schedule/", admin_schedule),
    path("admin/schedule/detail/", admin_schedule_detail),
    path("admin/csv-import/", admin_csv_import),
    path("admin/impersonate/", admin_impersonate),
    path("admin/stats/", admin_stats),
    path("admin/events/", admin_events),
    path("admin/events/detail/", admin_event_detail),
    path("admin/holidays/", admin_holidays),
    path("admin/holidays/detail/", admin_holiday_detail),
    path("events/", public_events),
    path("teacher/study-hall/", teacher_study_hall),
    path("teacher/study-hall/students/", teacher_study_hall_students),
    path("teacher/study-hall/attendance/", teacher_study_hall_attendance),
]
