from django.urls import path

from .views import auth_views, student_views, teacher_views, admin_views, schedule_views, timetable_views

urlpatterns = [
    # Auth
    path("login/", auth_views.login),
    path("me/", auth_views.me),
    path("me/avatar/", auth_views.upload_avatar),
    # Student
    path("grades/", student_views.grades),
    path("subjects/", student_views.subjects),
    path("diary/", student_views.diary_entries),
    path("attendance/", student_views.attendance),
    path("announcements/", student_views.announcements),
    path("behavioral/", student_views.behavioral_entries),
    # Schedule & events
    path("schedule/", schedule_views.schedule),
    path("events/", schedule_views.public_events),
    # Teacher
    path("teacher/class-students/", teacher_views.teacher_class_students),
    path("teacher/attendance/", teacher_views.teacher_attendance),
    path("teacher/marks/", teacher_views.teacher_marks),
    path("teacher/grades/add/", teacher_views.teacher_add_grade),
    path("teacher/grades/edit/", teacher_views.teacher_edit_grade),
    path("teacher/grades/delete/", teacher_views.teacher_delete_grade),
    path("teacher/homework/add/", teacher_views.teacher_add_homework),
    path("teacher/homework/update/", teacher_views.teacher_update_homework),
    path("teacher/homework/delete/", teacher_views.teacher_delete_homework),
    path("teacher/homework/completions/", teacher_views.teacher_homework_completions),
    path("teacher/behavioral/add/", teacher_views.teacher_add_behavioral),
    path("teacher/behavioral/delete/", teacher_views.teacher_delete_behavioral),
    path("teacher/class-stats/", teacher_views.teacher_class_stats),
    path("teacher/student-comments/", teacher_views.teacher_student_comments),
    path("teacher/reports/", teacher_views.teacher_reports),
    path("teacher/study-hall/", teacher_views.teacher_study_hall),
    path("teacher/study-hall/students/", teacher_views.teacher_study_hall_students),
    path("teacher/study-hall/attendance/", teacher_views.teacher_study_hall_attendance),
    path("teacher/substitutes/", teacher_views.teacher_substitutes),
    path("teacher/substitutes/classes/", teacher_views.teacher_substitute_classes),
    path("teacher/substitutes/detail/", teacher_views.teacher_substitute_detail),
    path("teacher/events/", teacher_views.teacher_events),
    path("teacher/events/detail/", teacher_views.teacher_event_detail),
    # Admin
    path("admin/stats/", admin_views.admin_stats),
    path("admin/impersonate/", admin_views.admin_impersonate),
    path("admin/classes/", admin_views.admin_classes),
    path("admin/classes/detail/", admin_views.admin_class_detail),
    path("admin/subjects/", admin_views.admin_subjects),
    path("admin/subjects/detail/", admin_views.admin_subject_detail),
    path("admin/users/", admin_views.admin_users),
    path("admin/users/detail/", admin_views.admin_user_detail),
    path("admin/teacher-assignments/", admin_views.admin_teacher_assignments),
    path("admin/teacher-assignments/delete/", admin_views.admin_teacher_assignment_delete),
    path("admin/student-subjects/", admin_views.admin_student_subjects),
    path("admin/student-subjects/delete/", admin_views.admin_student_subject_delete),
    path("admin/schedule/", admin_views.admin_schedule),
    path("admin/schedule/detail/", admin_views.admin_schedule_detail),
    path("admin/csv-import/", admin_views.admin_csv_import),
    path("admin/events/", admin_views.admin_events),
    path("admin/events/detail/", admin_views.admin_event_detail),
    path("admin/holidays/", admin_views.admin_holidays),
    path("admin/holidays/detail/", admin_views.admin_holiday_detail),
    path("admin/attendance-flags/", admin_views.admin_attendance_flags),
    path("admin/student-lookup/", admin_views.admin_student_lookup),
    path("admin/classes/credentials/", admin_views.admin_class_credentials),
    path("admin/dedupe-students/", admin_views.admin_dedupe_students),
    # Timetable generation
    path("timetable/generate/", timetable_views.generate_timetable),
    path("timetable/", timetable_views.get_timetable),
    path("timetable/slot/", timetable_views.update_slot),
    path("timetable/class-data/", timetable_views.get_class_data),
    path("timetable/clear/", timetable_views.clear_timetable),
]
