-- ============================================================
--  Chartwell E-Diary – Supabase Schema (public)
--  WARNING: This schema is for context only and is not meant
--  to be run. It documents the actual database structure.
-- ============================================================

-- Students (one row per student-subject enrolment, denormalised)
-- user_id links to auth.users(id)
CREATE TABLE public.students (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Name"     text NOT NULL,
  user_id    uuid NOT NULL REFERENCES auth.users(id),
  "Surname"  text NOT NULL,
  "Gender"   boolean,
  year       smallint NOT NULL,
  "Letter"   text NOT NULL,
  "Subject"  bigint NOT NULL,
  "Mark"     text
);

-- Teachers
-- user_id links to auth.users(id)
CREATE TABLE public.teachers (
  id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id                uuid REFERENCES auth.users(id),
  class_teacher_grade    text,
  subject_teaching       text,
  class_teacher_letter   text
);

-- Subjects
CREATE TABLE public.subjects (
  "Subject ID" bigint PRIMARY KEY,
  name         text NOT NULL
);

-- Marks lookup (grade letters)
CREATE TABLE public.marks (
  id      bigint PRIMARY KEY,
  grade   text NOT NULL,
  letter  text
);

-- Diary entries
CREATE TABLE public.diary_entries (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    uuid NOT NULL REFERENCES auth.users(id),
  title      text,
  content    text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Temperatures (weather data)
CREATE TABLE public.temperatures (
  date        date,
  time        time,
  temperature text
);
